//Amount of money generated by one money tile-resource
const double TILE_MONEY_RATE = 75.0;

//Amount of energy generated by one energy tile-resource per second
const double TILE_ENERGY_RATE = 0.5;

//Amount of research progress points generated by one
//research tile-resource per second
const double TILE_RESEARCH_RATE = 0.75;

//Amount of labor generation per second by one labor tile-resource
const double TILE_LABOR_RATE = 1.0 / 60.0;
const double LABOR_ACHIEVE_THRESH = 200.0 * TILE_LABOR_RATE;

//Labor's worth of support ships to build per minute with defense
const double DEFENSE_LABOR_PM = 2.0;
